#!/usr/bin/env bash
require() {
hash "$@" || exit 127;
}
require cat java sleep 
./createwar
classpath=$(cat runjetty.cp)
java -cp "$classpath":dist/Webapps-2.0.0.jar launch.OneWebApp &
echo "Sleeping for 15 seconds..."
sleep 15
./tests
