#!/usr/bin/env bash
./setuptests
classpath=$(cat run.cp)
#java -cp "$classpath":dist/Webapps-2.0.0.jar launch.Main &
java -cp "$classpath":dist/Webapps-2.0.0.jar org.eclipse.jetty.embedded.OneWebApp &
echo "Sleeping for 15 seconds..."
sleep 15
echo "calling curl http://localhost:8080/Webapp/index.html..."
curl http://localhost:8080/Webapp/index.html \
  |& grep -c "Click me!" | xargs -I % echo % "line(s) found" 
echo "calling curl http://localhost:8080/Webapp/FirstServlet..."
curl http://localhost:8080/Webapp/FirstServlet \
  |& grep -c "A Simple Servlet" | xargs -I % echo % "line(s) found" 
