#!/usr/bin/env bash
./setuptests
classpath=$(cat run.cp)
#java -cp "$classpath":dist/Webapps-2.0.0.jar launch.Main &
java -cp "$classpath":dist/Webapps-2.0.0.jar org.eclipse.jetty.embedded.OneWebApp &
echo "Sleeping for 5 seconds..."
sleep 5000
echo "calling curl..."
curl http://localhost:8080/Webapp/index.html
