#!/usr/bin/env bash
mkdir -p webapp/WEB-INF/classes/servlets
mkdir -p webapp/WEB-INF/lib
mkdir -p webapp/META-INF
cp web.xml webapp/WEB-INF
cp servlets/*.class webapp/WEB-INF/classes/servlets
awk '$1=$1' FS=":" OFS="\n" ../derby.cp \
  | parallel -I% cp % ./webapp/WEB-INF/lib
(cd webapps && jar -cvf ../dist/WebApps.war *)
classpath=$(cat run.cp)
java -cp "$classpath":. launch.Main &

