#!/usr/bin/env bash
usage()
{
  echo "Usage: $0 filepath"
  echo "filepath - path to java file"
  exit 1
}

declare -i res=0
file="$1"

if [ "$#" -ne 1 ] || ! [ -f "$file" ]; 
then
  usage
fi

filePrefix=$(basename -s .java "$file")
./astdumpcmd --file "$file" -PrenderProlog=false -PrenderCommonAttributes=true \
  | tee "$filePrefix".xml 
res=$?
exit $res
