#!/usr/bin/env bash
declare -r classpathFile="pmd.cp"
declare -r mainClass="net.sourceforge.pmd.util.treeexport.TreeExportCli"

java -cp @"$classpathFile" "$mainClass" "$@" \
|| { exitCode="$?";echo "$0 exited with error code $exitCode"; exit "$exitCode";}
res=$?
exit $res
