#!/usr/bin/env bash
# shellcheck disable=SC2155
require() {
  hash "$@" || exit 127
}
require java cat readlink dirname
declare -r classpathFile="pmd.cp"
declare -r mainClass="net.sourceforge.pmd.cli.PmdCli"
declare -r path="$(dirname "$(readlink -f "$0")")"
declare -r classpath="$(cat "${path}/${classpathFile}")"

java -cp "$classpath" "$mainClass" ast-dump "$@" ||
  {
    exitCode="$?"
    echo "$0 exited with error code $exitCode"
    exit "$exitCode"
  }
exit $?
