#!/usr/bin/env bash
# shellcheck disable=SC2155
require() {
  hash "$@" || exit 127
}
require java curl
bndVersion="6.4.1"
jarURL="https://bndtools.jfrog.io/artifactory/libs-snapshot/biz/aQute/bnd/biz.aQute.bnd/${bndVersion}/biz.aQute.bnd-${bndVersion}.jar"
jarPath="lib/biz.aQute.bnd-${bndVersion}.jar"
curl --silent -o "$jarPath" "$jarURL" -C -
java -jar "$jarPath" ||
  {
    exitCode="$?"
    echo "$0 exited with error code $exitCode"
    exit "$exitCode"
  }
exit $?
