#!/usr/bin/env bash
######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : buildjall
# @created     : Thursday May 02, 2019 17:40:19 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description : 
######################################################################
require() {
hash "$@" || exit 127
}
require rm find parallel

rm -f ./*.jar
find . -mindepth 2 -name "*.class" -type f \
  ! -path "**/.git/**" -delete
find . -maxdepth 1 -type d -name "[[:upper:]]*" | \
  parallel --joblog buildj.log -j 5 -I% --max-args 1 ./buildj %
exit $?
