#!/bin/bash

#######################################################################
#@author: Linus Fernandes(linusfernandes @gmail.com)
# @file: buildj
## @created: Friday May 03, 2019 21: 20: 25 IST
# @copyright: Copyright(c) Linus Fernandes
## @description: 
######################################################################
usage() {
        echo "usage: buildj dir"
        echo "dir - Project directory, must exist"
        exit 1
}


isJVM ()
{
  type jar &>/dev/null
  return $?
}

createJar()
{
  cd "$proj" || echo "cannot cd to $proj";
  jarFile="$proj-$version.jar"
  if [ ! -e "$manifestFile" ] 
  then
    echo "$manifestFile does not exist. Run ant manifest in $proj."
    exit 1
  fi
  readarray -t args < <(find . -name "*.class" \
    ! -path "**/.git/**" -type f)
  jar cfm "$jarFile" "$manifestFile" \
    "${args[@]}" || \
    { echo "Error creating jar output: $jarFile";exit 1; }
  jarRes=$? 
  [ -e "$jarFile" ] && cp "$jarFile" .. \
    && mkdir -p "$distDir" && mv "$jarFile" "$distDir" || \
    { echo "Error moving jar file to $proj/$distDir"; }
  cd ..
  exit 0
}

readVersion()
{
  [ -e "$versionFile" ] && \
      { version=$(cat "$versionFile") || \
      echo "Unable to read $versionFile";}
}

readOptions()
{
  [ -e "$proj"/"$optionsFile" ] && \
      { readarray -t options < <(cat "$proj"/"$optionsFile") || \
      echo "Unable to read $proj/$optionsFile";}
}

proj=$1
ver="1.8"
version="0.0.0"
declare -r optionsFile=".options"
declare -a options
declare -r distDir="dist"
declare -r manifestFile="manifest.mf"
declare -r verFile=".ver"
declare -r versionFile=".version"
declare -r verErrMsg="Unable to read $proj/$verFile"
declare -r archiveErrMsg="Unable to create executable archive"
declare -i SUCCESS=0
declare -i jarRes=0
isJVM
jvm=$?
if [ -z "$proj" ] || [ ! -d "$proj" ]
  then
    usage
else
    echo "$proj"
    [ -e "$proj"/"$verFile" ] && \
      { ver=$(cat "$proj"/"$verFile") || \
      echo "$verErrMsg";}
    readOptions
    readarray -t javasrcs \
      < <(find "$proj" -name "*.java" -type f)
    javac -Xlint:all ${options[@]} -source "$ver" -target "$ver" \
    -cp "$proj" \
    "${javasrcs[@]}"
    success=$?
    if [[ $success -eq SUCCESS ]]
      then
        readVersion
      if [[ $jvm -eq SUCCESS ]]
        then
        createJar
      else
        echo "$archiveErrMsg"
        success=1
      fi
    fi
fi
exit $((success+jarRes))
