#! /usr/bin/env bash
# display usage
[ $# -eq 0 ] && { echo "Usage: $0 <File Name without extension> options";exit 1; }
`rm -f $1.dex $1.class`
`ecj $1.java`
`dx --dex --output=$1.dex $1.class`
[ -e $1.dex ] && { dalvikvm -cp $1.dex $1;exit 0; }
