#! /usr/bin/env bash

######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : buildall
# @created     : Thursday May 02, 2019 17:40:19 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description : 
######################################################################

rm -f *.dex
rm -f *.jar
find . -name "*.class" -type f \
  ! -path "*.git*" -delete
find . -maxdepth 1 -type d \
  ! -path "*git*" ! -path . | \
  parallel -I% --max-args 1 ./build %
exit $?

