#!/usr/bin/env bash
require() {
  hash "$@" || exit 127
}
require find parallel dirname readlink
path="$(dirname "$(readlink -f "$0")")"
find . -maxdepth 1 -type d -name "[[:upper:]]*" |
  parallel --joblog buildant.log -I% --max-args 1 -j 5 \
    "${path}/buildant" %
