#!/bin/bash
usage()
{
  echo "Usage: $0 dir"
  echo "dir - Project directory"
  exit 1
}
if [ "$#" -ne 1 ] || ! [ -d "$1" ]; 
then
  usage
fi

#clang-format -i -style=Google -sort-includes \

clang-format -i -style=file -sort-includes \
`find $1 -type f -name "*.java"`
exit $?
