#!/usr/bin/env bash
declare -r classpathFile="cs.cp"
declare -r mainClass="com.puppycrawl.tools.checkstyle.Main"

java -cp @"$classpathFile" "$mainClass" "$@" \
|| { exitCode="$?";echo "$0 exited with error code $exitCode"; exit "$exitCode";}
res=$?
exit $res
