#!/usr/bin/env bash
usage()
{
  echo "Usage: $0 dir javafile"
  echo "dir - Project directory"
  echo "javafile - Java file"
  exit 1
}

readOptions()
{
  [ -e "$proj"/"$optionsFile" ] && \
      { readarray -t options < <(cat "$proj"/"$optionsFile") || \
      echo "Unable to read $proj/$optionsFile";}
}

if [ "$#" -lt 1 ] || ! [ -d "$1" ]; 
then
  usage
fi

proj=$1
declare -r optionsFile=".csoptions"
declare -a options
output_file="cs.errors"
declare -r classpathFile=$(realpath "cs.cp")
java_file=""
mainClass="com.puppycrawl.tools.checkstyle.Main"
echo "$1"
if [ -n "$2" ]
  then
    java_file="$2"
fi
if [ ! -e "$proj/$java_file" ]
  then
    echo "$proj/$java_file not found."
    usage
fi

if [ ! -e "$classpathFile" ]
  then
    echo "$classpathFile cannot be found. Run ant in root directory to generate file."
    usage
fi

readOptions
(set -o pipefail; cd "$1" && \
java -cp @"$classpathFile" \
"$mainClass" \
${options[@]} \
-t \
"$java_file");
exit $?
