#!/bin/bash
function usage()
{
  echo "usage: checkstyleall {rulesfile}"
  echo "rulesfile: The xml file that lists the rules that checkstyle will use."
  echo "google_checks.xml is the default rules file."
  exit 1
}
rules_file="google_checks.xml"
if [ ! -z $1 ]
  then
    rules_file=$1
fi
if [ ! -e $rules_file ]
  then
    echo "$rules_file cannot be found."
    usage
fi
java -jar \
lib/checkstyle-8.20-all.jar \
-c $rules_file \
`find . -mindepth 2 -type f -name "*.java"`
exit $?
