#!/usr/bin/env bash
usage()
{
  echo "Usage: $0 dir rulesfile"
  echo "dir - Project directory"
  echo "rulesfile - Rules file"
  exit 1
}

readOptions()
{
  [ -e "$proj"/"$optionsFile" ] && \
      { readarray -t options < <(cat "$proj"/"$optionsFile") || \
      echo "Unable to read $proj/$optionsFile";}
}

readExclusions()
{
  [ -e "$proj"/"$exclusionsFile" ] && \
      { readarray -t exclusions < <(cat "$proj"/"$exclusionsFile") || \
      echo "Unable to read $proj/$exclusionsFile";}
}

set -o noglob
declare -r optionsFile=".csoptions"
declare -a options
declare -r exclusionsFile=".exclusions"
declare -a exclusions
rules_file=$(realpath "csrules.xml")
declare -r properties_file=$(realpath "checkstyle.properties")
declare -r output_file="cs.errors"
declare -r classpathFile=$(realpath "cs.cp")
declare -r mainClass="com.puppycrawl.tools.checkstyle.Main"

if [ "$#" -lt 1 ] || ! [ -d "$1" ]; 
then
  usage
fi

proj=$1
echo "$1"
if [ -n "$2" ]
  then
    rules_file=$(realpath $2)
fi
if [ ! -e "$rules_file" ]
  then
    echo "$rules_file cannot be found."
    usage
fi

if [ ! -e "$classpathFile" ]
  then
    echo "$classpathFile cannot be found. Run ant in root directory to generate file."
    usage
fi

if [ ! -e "$properties_file" ]
  then
    echo "$properties_file not found. Creating..."
    touch "$properties_file" || \
      echo "Unable to create $properties_file"
    echo "Create/Modify $properties_file to configure checkstyle"
fi
readOptions
readExclusions
cd "$proj"
readarray -t args \
  < <(find . -type f -name "*.java" \
${exclusions[@]} \
  -not -path "./docs" -not -path "./dist")
java -cp @"$classpathFile" \
"$mainClass" \
${options[@]} \
-c "$rules_file" -d \
-p "$properties_file" \
-o "$output_file" \
"${args[@]}"
set +o noglob
exit $?
