#!/usr/bin/env bash
usage()
{
  echo "Usage: $0 dir"
  echo "dir - Project directory"
  exit 1
}

require() {
hash "$@" || exit 127
}
require java find cat tee grep 

declare -r outputFile="ckjm.report"
declare -r conciseFile="ckjmconcise.report"
declare -r classpathFile="ckjm_ext.cp"
declare -r mainClass="gr.spinellis.ckjm.MetricsFilter"

if [ "$#" -ne 1 ] || ! [ -d "$1" ]; 
then
  usage
fi

echo "$1"
proj="$1"

# shellcheck disable=SC2155
classpath="$(cat "$classpathFile"):."
res="$(cd "$proj" || exit $?
java -cp "$classpath" \
    "$mainClass" \
    "$(find . -name '*.class')" \
    | tee "$outputFile" \
    || { exitCode="$?";echo "$0 exited with error code $exitCode";exit "$exitCode";}
  )"
echo "ClassName WMC DIT NOC CBO RFC LCOM Ca Ce NPM LCOM3 LOC DAM MOA MFA CAM IC CBM AMC" > "$conciseFile"
grep '^[^[:space:]]\{1\}' "$outputFile" >> "$conciseFile"
exit "$res"
