#!/bin/bash
declare -r errFile="cpdxml.errors"
declare -r format="text"
declare -r language="xml"
declare -r classpathFile="pmd.cp"
declare -r mainClass="net.sourceforge.pmd.cpd.CPD"

java -cp @"$classpathFile" \
"$mainClass" \
--minimum-tokens 100 \
--format "$format" \
--language "$language" \
--files . \
--exclude **/build.xml \
| tee "$errFile" \
|| { echo "Error running $0"; exit 1;}
res=$?
exit $res
