#!/usr/bin/env bash
require() {
hash "$@" || exit 127
}
require find parallel sh 
find . -maxdepth 1 -type d -name "[[:upper:]]*" | \
  parallel --joblog delombok.log --delay 1 -j 5 -I% sh -c 'echo && ./delombok %'
exitcode="$?"
exit "$exitcode"
