#!/usr/bin/env bash
require() {
hash "$@" || exit 127;
}
require find awk grep
grep -src "^\[.*\].*" "$(find . -name 'cs.errors')" |
  grep -v ':0$' \
  | awk -F ":" '{ printf("%s %s\n",$2,$1) }'
exit $?
