#!/usr/bin/env bash
require() {
hash "$@" || exit 127
}
require java realpath cat 
# shellcheck disable=SC2155
declare -r classpathFile="$(realpath 'spotbugs.cp')"
# shellcheck disable=SC2155
declare -r classpath="$(cat "$classpathFile")"
declare -r mainClass="edu.umd.cs.findbugs.FindBugs2"
declare -r pluginjars="spotbugs-plugin.cp"

java -cp "$classpath" "$mainClass" \
  -pluginList "<$(cat $pluginjars)>" "$@" \
|| { exitCode="$?";echo "$0 exited with error code $exitCode"; exit "$exitCode";}
exit $?
