#!/usr/bin/env bash
usage()
{
  echo "Usage: $0 dir"
  echo "dir - Project directory"
  exit 1
}

require() {
hash "$@" || exit 127
}
require java realpath cat 

declare -r errFile="spotbugs.errors"
declare -r classpathFile="$(realpath 'spotbugs.cp')"
declare -r classpath="$(cat "$classpathFile")"
declare -r mainClass="edu.umd.cs.findbugs.FindBugs2"
declare -r pluginjars="spotbugs-plugin.cp"

if [ "$#" -ne 1 ] || ! [ -d "$1" ]; 
then
  usage
fi

java -cp "$classpath" "$mainClass" \
  -pluginList "<$(cat $pluginjars)>" \
  -auxclasspath "$1" -quiet -adjustExperimental \
  -output "${1}/${errFile}" \
  -xml:withMessages -workHard \
  -experimental -nested:true -timestampNow \
  -longBugCodes -progress -dontCombineWarnings \
  "$1" \
|| { exitCode="$?";echo "$0 exited with error code $exitCode"; exit "$exitCode";}
exit $?
