#!/usr/bin/env bash
usage()
{
  echo "Usage: $0 dir"
  echo "dir - Project directory"
  exit 1
}

readOptions()
{
  [ -e "$proj"/"$optionsFile" ] && \
      { readarray -t options < <(cat "$proj"/"$optionsFile") || \
      echo "Unable to read $proj/$optionsFile";}
}

if [ "$#" -ne 1 ] || ! [ -d "$1" ]; 
then
  usage
fi
proj=$1
declare -r optionsFile=".formatoptions"
declare -a options
declare -r classpathFile="gformat.cp"
declare -r mainClass="com.google.googlejavaformat.java.Main"
declare -i res=0

if [ ! -e "$classpathFile" ]
  then
    echo "$classpathFile cannot be found. Run ant in root directory to generate file."
    usage
fi

readOptions
set +o noglob
printf -v findCmd '%q ' find $1 -type f -name '*.java' ${options[@]}
readarray -t args < <(eval $findCmd)
if [ ${#args[@]} -ne 0 ]; then
  java -cp @"$classpathFile" "$mainClass" \
    --set-exit-if-changed -i \
    "${args[@]}"
  res="$?"
fi
set -o noglob
exit "$res"
