#!/usr/bin/env bash
require() {
hash "$@" || exit 127;
}
require find 
declare -i errs=0
cmd="find . -maxdepth 1 -type d -name '[[:upper:]]*'"
readarray -t dirs < <(eval "$cmd")
for dir in "${dirs[@]}"
	do
	echo "$dir"
  ./format "$dir"
  errs="$errs+$?"
done
exit $errs
