#!/bin/bash
declare -r classpathFile="gformat.cp"
declare -r mainClass="com.google.googlejavaformat.java.Main"
readarray -t args \
  < <(find . -mindepth 2 \
  -type f -name "*.java")
java -cp @"$classpathFile" "$mainClass" \
  --set-exit-if-changed -i \
  "${args[@]}"
exit $?
