#!/usr/bin/env bash
usage()
{
  echo "Usage: $0 dir"
  echo "dir - Project directory"
  exit 1
}

require() {
hash "$@" || exit 127;
}
require realpath java find tee cat
declare -r outputFile="javancss.report"
# shellcheck disable=SC2155
declare -r classpathFile="$(realpath "javancss.cp")"
declare -r mainClass="javancss.Main"
# shellcheck disable=SC2155
declare -r classpath="$(cat "$classpathFile")"
if [ "$#" -ne 1 ] || ! [ -d "$1" ]; 
then
  usage
fi

echo "$1"
proj="$1"

res=$(cd "$proj" || exit $?
java -cp "$classpath" \
  "$mainClass" -all \
  "$(find . -name "*.java")" \
  | tee "$outputFile" \
  || { exitCode="$?";echo "$0 exited with error code $exitCode";cd ..; exit "$exitCode";}
)
exit "$res"
