#!/usr/bin/env bash
require() {
hash "$@" || exit 127;
}
require javac
regex="^javac ([1-9]{1,2})\.[0-9]+\.[0-9]+$"
output=$(javac --version)
if [[ $output =~ $regex ]]
  then
    echo "${BASH_REMATCH[1]}"
    exit 0
  else
    exit 1
fi
