#!/usr/bin/env bash
require() {
hash "$@" || exit 127;
}
require find parallel sh
find . -maxdepth 1 -type d -name "[[:upper:]]*" | \
  parallel --joblog lizard.log --delay 1 -j 1 -I% sh -c 'echo && ./lizard %'
exitcode="$?"
exit "$exitcode"
