#!/usr/bin/env bash
require() {
  hash "$@" || exit 127
}
require lizard find tee paste
declare -r errFile="lizardcpd.errors"

lizard -w -Eduplicate \
  "$(find . -name '*.java' | paste -sd ' ')" |
  tee "$errFile" ||
  {
    echo "Error running $0"
    exit 1
  }
exit $?
