#!/usr/bin/env bash
require() {
  hash "$@" || exit 127
}
require lizard find paste
lizard -w -Ewordcount \
  "$(find . -name '*.java' | paste -sd ' ')" ||
  {
    echo "Errors/warnings found running $0"
    exit 1
  }
exit $?
