#!/usr/bin/env bash
require() {
hash "$@" || exit 127;
}
require java cat realpath
# shellcheck disable=SC2155
declare -r classpathFile="$(realpath 'lombok.cp')"
# shellcheck disable=SC2155
declare -r classpath="$(cat "$classpathFile")"
declare -r mainClass="lombok.launch.Main"

java -cp "$classpath" "$mainClass" "$@" \
|| { exitCode="$?";echo "$0 exited with error code $exitCode"; exit "$exitCode";}
exit $?
