#!/usr/bin/env bash

######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : mvpackagedirs
# @created     : Friday May 03, 2019 08:13:05 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description : Creates package folders and moves java source to these directories.
#                Behaviour unspecified if first line in file does not have package directive
#                Use from directory containing source files.
#                Also creates package-info.java if it does not exist already.
######################################################################
package=""
pkgInfoFile="package-info.java"
dir=""
declare -i count
readarray -t args < <(find . -maxdepth 1 \
  -name "*.java" -type f \
  ! -path "**/.git/**" ! -path .)
for file in "${args[@]}"
  do
    count=$(head -1 "$file" | grep -c 'package')
    if [ $count -ne 0 ]
    then
      package=$(head -1 "$file" | grep 'package' | awk '{print $2}' | sed 's/;//')
      dir=$(mkpackagedirs "$package")
      mv "$file" "$dir"
      if [ -e "$dir"/"$pkgInfoFile" ]
      then
        continue
      else
        echo "package $package;">"$dir/$pkgInfoFile"
        echo "Created $dir/$pkgInfoFile"
      fi
    fi
done
exit 0
