#! /usr/bin/env bash
usage()
{
  echo "Usage: $0 dir"
  echo "dir - Project directory"
  exit 1
}
if [ "$#" -ne 1 ] || ! [ -d "$1" ]; 
then
  usage
fi
declare -r rulesFile="pmdrules.xml"
declare -r cacheFile="pmd.cache"
declare -r errFile="pmd.errors"
declare -r format="text"
declare -i threads=5
# run.sh must be in the search path
echo "Start time :" `date +"%r"`
run.sh pmd -d $1 -R $rulesFile -f $format \
-failOnViolation false -cache $1/$cacheFile \
-reportfile $1/$errFile \
-auxclasspath $1 \
-t $threads \
|| { echo "Error running $0"; exit 1;}
res=$?
echo "End time:" `date +"%r"`
exit $res
