#!/bin/bash
declare -i errs=0
readarray -t dirs < <\
(find . -maxdepth 1 \
-type d -name "[[:upper:]]*")
for dir in "${dirs[@]}"
	do
	echo "$dir"
  ./pmd "$dir"
  errs="$errs+$?"
done
./findpmderrors
exit $errs
