#!/bin/bash
declare -i errs=0
readarray -t dirs < <\
(find . -maxdepth 1 \
-type d -name "[[:upper:]]*")
for dir in "${dirs[@]}"
	do
	echo "$dir"
  ./pmd "$dir"
  exitcode="$?"
  if [[ "$exitcode" -gt 0 ]]
  then
    case "$errs" in
      0) errs="$exitcode" ;;
      1) ;;
      4) errs="$exitcode" ;;
    esac
  fi
done
./findpmderrors
exit $errs
