#!/usr/bin/env bash
declare -i errs=0
cmd="find . -maxdepth 1 -type d -name '[[:upper:]]*'"
readarray -t dirs < <(eval "$cmd")
echo "Command ExitCode" > pmd.log
for dir in "${dirs[@]}"
do
  echo "$dir"
  echo -n "'./pmd $dir'" >> pmd.log
  ./pmd "$dir"
  exitcode="$?"
  echo " $exitcode" >> pmd.log
  if [[ "$exitcode" -gt 0 ]]
  then
    case "$errs" in
      0) errs="$exitcode" ;;
      1) ;;
      4) errs="$exitcode" ;;
    esac
  fi
done
./findpmderrors
exit $errs

