#!/usr/bin/env bash
# shellcheck disable=SC2155
require() {
  hash "$@" || exit 127
}
path() {
  dirname "$(readlink -f "$1")"
}
require java cat readlink dirname realpath
dir="$(path "$0")"
declare -r classpathFile="${dir}/pmd.cp"
declare -r slf4jclasspathFile="${dir}/slf4j-simple.cp"
declare -r classpath="$(cat "$classpathFile")"
declare -r slf4jclasspath="$(cat "$slf4jclasspathFile")"
declare -r mainClass="net.sourceforge.pmd.cli.PmdCli"

java -cp "${classpath}:${slf4jclasspath}" "$mainClass" check "$@" ||
  {
    exitCode="$?"
    echo "$0 exited with error code $exitCode"
    exit "$exitCode"
  }
exit $?
