#!/usr/bin/env bash
usage()
{
  echo "Usage: $0 dir"
  echo "dir - Project directory"
  exit 1
}

readOptions()
{
  [ -e "$proj"/"$optionsFile" ] && \
      { readarray -t options < <(cat "$proj"/"$optionsFile") || \
      echo "Unable to read $proj/$optionsFile";}
}

require() {
hash "$@" || exit 127;
}
require cat find prettier

if [ "$#" -ne 1 ] || ! [ -d "$1" ]; 
then
  usage
fi

proj=$1
declare -r optionsFile=".formatoptions"
declare -a options
declare -i res=0

readOptions
set +o noglob
printf -v findCmd '%q ' find "$proj" -type f -name '*.java' "${options[@]}"
readarray -t args < <(eval "$findCmd")
if [ "${#args[@]}" -ne 0 ]; then
  prettier --write "${args[@]}"
  res="$?"
fi
set -o noglob
exit "$res"
