#!/usr/bin/env bash
require() {
  hash "$@" || exit 127
}
path() {
  dirname "$(readlink -f "$1")"
}
require find prettier dirname readlink
dir="$(path "$0")"
(
  cd "$dir" || exit $?
  readarray -t args < <(find . -mindepth 2 -type f -name "*.java")
  prettier --write "${args[@]}"
)
exit $?
