#!/usr/bin/env bash
require() {
  hash "$@" || exit 127
}
path() {
  dirname "$(readlink -f "$1")"
}
require awk xargs cat dirname readlink
dir="$(path "$0")"
(
  cd "$dir" || exit $?
  ./findcserrors |
    awk '{print $2}' |
    xargs -I{} cat {}
)
exit $?
