#!/usr/bin/env bash
require() {
  hash "@" || exit 127
}
path() {
  dirname "$(readlink -f "$1")"
}
require find parallel dirname readlink nproc
dir="$(path "$0")"
(
  cd "$dir" || exit $?
  procs=$(nproc)
  find . -maxdepth 1 -type d -name "[[:upper:]]*" |
    parallel --joblog runant.log -j "$procs" -I% --max-args 1 \
      ./runant %
)
