#! /usr/bin/env bash

######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : runall
# @created     : Thursday May 02, 2019 17:41:08 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description : 
######################################################################
find . -maxdepth 1 -type d \
  ! -path "*git*" ! -path . | \
  parallel -I% sh -c 'echo && ./run %'
exit $?
