#! /usr/bin/env bash

######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : runall
# @created     : Thursday May 02, 2019 17:41:08 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description : 
######################################################################
#errors=0
#for dir in $(find . -maxdepth 1 -type d ! -path "*.git*" ! -path . )
 # do
  #  echo $dir
   # ./run $dir
    #errors=$( expr $errors + $? )
  #done
#exit $errors
find . -maxdepth 1 -type d ! -path "*git*" ! -path . | parallel -I% sh -c 'echo && ./run %'
exit $?
