#!/usr/bin/env bash
######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : runjall
# @created     : Friday Jul 05, 2019 17:41:08 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description :
######################################################################
require() {
  hash "$@" || exit 127
}
path() {
  dirname "$(readlink -f "$1")"
}
require find parallel dirname readlink nproc
dir="$(path "$0")"
(
  cd "$dir" || exit $?
  procs=$(nproc)
  find . -maxdepth 1 -type d -name "[[:upper:]]*" |
    parallel --joblog runj.log -j "$procs" -I% bash -c 'echo && ./runj %'
)
exit $?
