#! /usr/bin/env bash

######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : run
# @created     : Thursday May 02, 2019 16:31:33 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description : 
######################################################################

usage ()
{
  echo 'Usage: run <dir> <class>'
  echo 'dir - project directory. Must exist'
  echo 'class - full name including package name of the main class. Overrides contents of .main under project directory.'
  exit 1
}

setUp ()
{
	cd "$proj" || \
    { echo "Unable to access folder $proj";exit 1;}
	[ -e "$setupScript" ] && \
    { ./"$setupScript" || \
      { \
        echo "Error running setup script";\
        exit 1;\
      }\
    }
	cd ..
}

tearDown ()
{
	cd "$proj" || \
    { echo "Unable to access folder $proj";exit 1;}
	[ -e "$teardownScript" ] && \
    {\
      ./"$teardownScript" || \
      {\
        echo "Error running teardown script";\
        exit 1;\
      }\
    }
	cd ..
}

isDalvik ()
{
  type dalvikvm &>/dev/null
  return $?
}

isJVM ()
{
  type java &>/dev/null
  return $?
}

runDalvik()
{
  dexFile="$proj-$version.dex"
  if [ -e "$dexFile" ] 
    then
    setUp
    echo "Main class(es): $main"
    echo
    echo "$main" | while read -r a; do 
      echo "Running $a...";echo
      dalvikvm "$runOptions" -cp "$dexFile $a";
      echo
    done
    tearDown;
    exit 0;
  else
    echo "$dexFile does not exist. Run build or buildall."
    exit 1
  fi
}

runJVM()
{
  jarFile="$proj-$version.jar"
  if [ -e "$jarFile" ]
    then
      setUp
      echo "Main class(es): $main"
     for a in "${main[@]}";
     do
      if [[ -z "$a" ]]
      then
        continue
      fi
      if [[ "$a" =~ ^#.* ]]
      then
        continue
      fi
      echo "Running $a...";echo
      cd "$proj"
      printf -v cmdPrefix '%q ' java $runOptions -cp ../$jarFile:. 
      eval "$cmdPrefix $a"
      cd ..
    done
    tearDown;
      exit 0;
    else
      echo "$jarFile does not exist. Run buildj or buildjall."
    exit 1
  fi
}

readVersion()
{
  [ -e "$versionFile" ] && \
      { version=$(cat "$versionFile") || \
      echo "Unable to read $versionFile";}
}

readRunOptions()
{
  [ -e "$proj/$runOptionsFile" ] && \
      { runOptions=$(cat "$proj"/"$runOptionsFile") || \
      echo "Unable to read $proj/$runOptionsFile";}
}

declare -r setupScript="setup"
declare -r teardownScript="teardown"
declare -r nomainFile=".nomain"
declare -r mainFile=".main"
declare -a main
proj="$1"
if [ -z "$proj" ]
  then
    usage
fi
if [ -e "$proj/$nomainFile" ]
  then
    echo "$proj"
    echo "Not an executable project."
    exit 1
fi

declare -r versionFile=".version"
declare -r runOptionsFile=".runoptions"
runOptions=""
version="0.0.0"
main[0]="$2"
if [ -z "$2" ]
then
  readarray main < "$proj"/"$mainFile" || \
    { echo "Error reading $proj/$mainFile";usage; }
fi
echo "$proj"
readVersion
readRunOptions
isDalvik
dalvik=$?
if [ $dalvik -eq 0 ]
  then
    runDalvik
fi

isJVM
jvm=$?
if [ $jvm -eq 0 ]
  then
    printf '%s\n' "${main[@]}"
    runJVM
fi

usage
