#!/usr/bin/env bash

declare -r classpathFile="/data/data/com.termux/files/home/LearnJava/saxon-he.cp"
declare -r mainClass="net.sf.saxon.Query"

if [ ! -e "$classpathFile" ]
  then
    echo "$classpathFile cannot be found. Run ant in root directory to generate file."
    usage
fi

java -cp @"$classpathFile" "$mainClass" "$@"
exit $?
