#!/usr/bin/env bash
require() {
hash "$@" || exit 127
}
require java cat 

declare -r classpathFile="$HOME/LearnJava/saxon-he.cp"
# shellcheck disable=SC2155
declare -r classpath="$(cat "$classpathFile")"
declare -r mainClass="net.sf.saxon.Query"

if [ ! -e "$classpathFile" ]
  then
    echo "$classpathFile cannot be found. Run ant in root directory to generate file."
    usage
fi

java -cp "$classpath" "$mainClass" "$@"
exit $?
