#!/usr/bin/env bash
# shellcheck disable=SC2155
require() {
  hash "$@" || exit 127
}
path() {
  dirname "$(readlink -f "$1")"
}
require java cat readlink dirname

declare -r classpathFile="$(path "$0")/saxon-he.cp"
declare -r mainClass="net.sf.saxon.Query"

if test ! -e "$classpathFile"; then
  echo "$classpathFile cannot be found. Run ant in root directory to generate file."
  usage
fi

declare -r classpath="$(cat "$classpathFile")"
java -cp "$classpath" "$mainClass" "$@"
exit $?
