#!/usr/bin/env bash
function require() {
 hash $@ || exit 127;
}
require rm cp ln realpath mv
if test -f .git/hooks/pre-commit; then
  mv .git/hooks/pre-commit .git/hooks/pre-commit
fi
ln -sfnv $(realpath git/hooks/pre-commit) .git/hooks/pre-commit
exit "$?"
