#!/usr/bin/env bash
# shellcheck disable=SC2155
require() {
  hash "@" || exit 127
}
path() {
  dirname "$(readlink -f "$1")"
}
require java cat readlink dirname
dir="$(path "$0")"
declare -r classpathFile="${dir}/spotbugs.cp"
declare -r classpath="$(cat "$classpathFile")"
declare -r mainClass="edu.umd.cs.findbugs.LaunchAppropriateUI"
declare -r pluginjars="${dir}/spotbugs-plugin.cp"
declare -r plugins="$(cat "$pluginjars")"

java -cp "$classpath" "$mainClass" \
  -pluginList "<${plugins}>" "$@" ||
  {
    exitCode="$?"
    echo "$0 exited with error code $exitCode"
    exit "$exitCode"
  }
exit $?
