#!/usr/bin/env bash
usage()
{
  echo "Usage: $0 dir"
  echo "dir - Project directory"
  exit 1
}

declare -r errFile="spotbugs.errors"
declare -r classpathFile="spotbugs.cp"
declare -r mainClass="edu.umd.cs.findbugs.LaunchAppropriateUI"
declare -r pluginjars="spotbugs-plugin.cp"

if [ "$#" -ne 1 ] || ! [ -d "$1" ]; 
then
  usage
fi

java -cp @"$classpathFile" "$mainClass" \
  -output "$1"/"$errFile" \
  -auxclasspath "$1" -quiet -adjustExperimental \
  -workHard \
  -experimental -nested:true -timestampNow \
  -longBugCodes -progress -dontCombineWarnings \
  -pluginList '<$(cat "$pluginjars")>' \
  "$1" \
|| { exitCode="$?";echo "$0 exited with error code $exitCode"; exit "$exitCode";}
res=$?
exit $res

