#!/usr/bin/env bash
require() {
  hash "$@" || exit 127
}
path() {
  dirname "$(readlink -f "$1")"
}
require dirname readlink
ivypath="$(path "$0")/ivycleanver"
eval "$ivypath org.apache.bcel $1"
eval "$ivypath org.apache.commons $1"
eval "$ivypath org.apache.logging $1"
eval "$ivypath org.apache.james $1"
eval "$ivypath org.apache.httpcomponents $1"
eval "$ivypath org.apache.geronimo.specs $1"
eval "$ivypath org.apache.derby $1"
eval "$ivypath org.apache-extras.beanshell $1"
eval "$ivypath org.apache.geronimo.genesis $1"
eval "$ivypath org.apache.geronimo.genesis.config $1"
eval "$ivypath org.apache.xmlgraphics $1"
eval "$ivypath org.apache.ws.commons.axiom $1"
eval "$ivypath org.apache $1"
eval "$ivypath org.apache.ant $1"
eval "$ivypath org.apache.ws $1"
eval "$ivypath org.apache.tomcat.embed $1"
eval "$ivypath org.apache.tomcat $1"
eval "$ivypath org.apache.logging.log4j $1"
