#!/usr/bin/env bash
start=$SECONDS+0
./updeps
ret="$?"
if [[ "$ret" == 0 ]]
then
end=( $SECONDS - $start  )
minutes=( $end/60 )
seconds=( $end%60 )
  echo "Completed in "$minutes" m "$seconds" s";
  exit 0
fi
exit "$ret"
