#!/bin/bash
declare -r configFileName="tidy.config"
configFilePath="$(find .. -maxdepth 2 -type f -name "$configFileName" ! -path "**/.git/**" -path "**/LearnJava/**")"
find . -maxdepth 2 -type f -name "*.xml" \
  ! -path "**/.git/**" \
  | parallel -j 5 -I% tidy -config "$configFilePath" \
  -quiet -xml -m %
exit $?
