#!/usr/bin/env bash
./antlr4 -package hello -o hello Hello.g4
./antlr4 -package hello -Dlanguage=Python3 -o hellopy3 Hello.g4
./antlr4 -package tee -Dlanguage=Java -o tee Tee.g4
./antlr4 -package 'expr' -Dlanguage=Java -o 'expr' Expr.g4

