#!/usr/bin/env bash
require() {
hash "$@" || exit 127;
}
require cp cat 
cp ../jcommander.cp run.cp
cp ../jcommander.cp compile.cp
echo -n ':' >> run.cp
echo -n ':' >> compile.cp
cat ../junit4.cp >> run.cp
cat ../junit4.cp >> compile.cp
