#!/usr/bin/env bash
usage()
{
  echo "Usage: $0 classname"
  echo "classname - FQCN"
  exit 1
}
require() {
hash "$@" || exit 127;
}
require java cat
cn="$1"

if [ "$#" -ne 1 ]; 
then
  usage
fi
java -cp "$(cat run.cp)" org.objectweb.asm.util.ASMifier "$cn" 
