#!/usr/bin/env bash
ps -ef | grep \
  'networking.DaytimeServer' | \
  awk '{print $2}' | head -1 \
  | parallel -I% kill %
echo $?
ps -ef | grep \
  'networking.TimeServer' | \
  awk '{print $2}' | head -1 \
  | parallel -I% kill %
echo $?
ps -ef | grep \
  'networking.MultithreadedDaytimeServer' | \
  awk '{print $2}' | head -1 \
  | parallel -I% kill %
echo $?
ps -ef | grep \
  'networking.PooledDaytimeServer' | \
  awk '{print $2}' | head -1 \
  | parallel -I% kill %
echo $?
ps -ef | grep \
  'networking.EchoServer' | \
  awk '{print $2}' | head -1 \
  | parallel -I% kill %
echo $?
ps -ef | grep \
  'networking.RandomPort' | \
  awk '{print $2}' | head -1 \
  | parallel -I% kill %
echo $?
ps -ef | grep \
  'networking.LoggingDaytimeServer' | \
  awk '{print $2}' | head -1 \
  | parallel -I% kill %
echo $?
