#!/usr/bin/env bash
ps -ef | grep \
  'networking.DaytimeServer' | \
  awk '{print $2}' | head -1 \
  | parallel -I% kill %
echo $?
ps -ef | grep \
  'networking.TimeServer' | \
  awk '{print $2}' | head -1 \
  | parallel -I% kill %
echo $?
