#!/usr/bin/env bash
java -cp . networking.DaytimeServer &
echo "Sleeping for 5 seconds again after DaytimeServer start..."
sleep 5
echo "Running DayTimeClient to port 1313"
java -cp . networking.DayTimeClient localhost 1313
echo "Killing DaytimeServer..."
ps -ef | grep \
  'networking.DaytimeServer' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
java -cp . networking.TimeServer &
echo "Sleeping for 5 seconds again after TimeServer start..."
sleep 5
echo "Running Time to port 3737"
java -cp . networking.Time localhost 3737
echo "Killing TimeServer..."
ps -ef | grep \
  'networking.TimeServer' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
java -cp . networking.MultithreadedDaytimeServer &
echo "Sleeping for 5 seconds again after MultithreadedDaytimeServer start..."
sleep 5
echo "Running DayTimeClient to port 1331"
java -cp . networking.DayTimeClient localhost 1331
echo "Killing MultithreadedDaytimeServer..."
ps -ef | grep \
  'networking.MultithreadedDaytimeServer' | 
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
java -cp . networking.PooledDaytimeServer &
echo "Sleeping for 5 seconds again after PooledDaytimeServer start..."
sleep 5
echo "Running DayTimeClient to port 3131"
java -cp . networking.DayTimeClient localhost 3131
echo "Killing PooledDaytimeServer..."
ps -ef | grep \
  'networking.PooledDaytimeServer' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
echo "Running SocketEchoServer to port 9999"
java -cp . networking.SocketEchoServer &
echo "Sleeping for 5 seconds again after SocketEchoServer start..."
sleep 5
echo "Running EchoClient to port 9999"
java -cp . networking.EchoClient localhost 9999 < echo.txt
echo "Killing SocketEchoServer..."
ps -ef | grep \
  'networking.SocketEchoServer' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
echo "Running EchoServer to port 7777"
java -cp . networking.EchoServer 7777 &
echo "Sleeping for 5 seconds again after EchoServer start..."
sleep 5
echo "Running Non-blocking EchoClient to port 7777"
sleep 5
echo "Hmm..no output??? I guess I'll have to write one now...."
echo "Killing EchoServer..."
ps -ef | grep \
  'networking.EchoServer' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
echo "Running RandomPort at well...random port..."
java -cp . networking.RandomPort &
echo "Sleeping for 5 seconds again after RandomPort server start..."
sleep 5
echo "Killing RandomPort..."
ps -ef | grep \
  'networking.RandomPort' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
java -Djava.util.logging.config.file=logging.properties -cp . networking.LoggingDaytimeServer 4141 &
echo "Sleeping for 5 seconds again after LoggingDaytimeServer start..."
sleep 5
echo "Running DayTimeClient to port 4141"
java -cp . networking.DayTimeClient localhost 4141
echo "Killing LoggingDaytimeServer..."
ps -ef | grep \
  'networking.LoggingDaytimeServer' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
java -Djava.util.logging.config.file=logging.properties -cp . networking.SingleFileHttpServer web.log 8080 &
echo "Sleeping for 5 seconds again after SingleFileHttpServer start..."
sleep 5
echo "Running curl to port 8080"
curl --url http://localhost:8080
echo "Killing SingleFileHttpServer..."
ps -ef | grep \
  'networking.SingleFileHttpServer' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
java -Djava.util.logging.config.file=logging.properties -cp . networking.Redirector http://www.maketimeforsports.com/ 8081 &
echo "Sleeping for 5 seconds again after Redirector start..."
sleep 5
echo "Running curl to port 8081"
curl --url http://localhost:8081
echo "Killing Redirector..."
ps -ef | grep \
  'networking.Redirector' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
java -Djava.util.logging.config.file=logging.properties -cp . networking.JHttp . 8082 &
echo "Sleeping for 5 seconds again after JHttp start..."
sleep 5
echo "Running curl to port 8082"
curl --url http://localhost:8082/web.log
echo "Running curl head request to port 8082"
curl -v -I http://localhost:8082/web.log
echo "Running wget head request to port 8082"
wget -S --spider http://localhost:8082/web.log
echo "Killing JHttp..."
ps -ef | grep \
  'networking.JHttp' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
java -cp . networking.SecureOrderTaker &
echo "Sleeping for 5 seconds again after SecureOrderTaker start..."
sleep 5
echo "Running SecureOrderPlacer to port 7000"
java -cp . networking.SecureOrderPlacer
echo "Killing SecureOrderTaker..."
ps -ef | grep \
  'networking.SecureOrderTaker' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
java -Djavax.net.ssl.keyStore=serverkeystore.jks \
  -Djavax.net.ssl.keyStorePassword=password \
  -Djavax.net.ssl.trustStore=servertruststore.jks \
  -Djavax.net.ssl.trustStorePassword=password \
  -cp . networking.MainClass &
echo "Sleeping for 5 seconds again after MainClass start..."
sleep 5
echo "Running SocketClientDemo to port 5432"
java -Djavax.net.ssl.keyStore=clientkeystore.jks \
	-Djavax.net.ssl.keyStorePassword=password \
	-Djavax.net.ssl.trustStore=clienttruststore.jks \
	-Djavax.net.ssl.trustStorePassword=password \
	-cp . networking.SocketClientDemo
echo "Killing MainClass..."
ps -ef | grep \
  'networking.MainClass' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
java -cp . networking.ServerEcho 7007 &
echo "Sleeping for 5 seconds again after ServerEcho start..."
sleep 5
java -cp . networking.ClientEcho 7007 < echo.txt
echo "Killing ServerEcho..."
ps -ef | grep \
  'networking.ServerEcho' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
java -cp . networking.ChargenServer 1991 &
echo "Sleeping for 5 seconds again after ChargenServer start..."
sleep 5
java -cp . networking.ChargenClient localhost 1991 > chargen.out &
echo "Running ChargenClient for 0.1 seconds only..."
sleep 0.1
ps -ef | grep \
  'networking.ChargenClient' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
echo "Killing ChargenServer..."
ps -ef | grep \
  'networking.ChargenServer' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
java -cp . networking.SocketServerExample &
echo "Running SocketServerExample for 5 seconds only..."
sleep 5
ps -ef | grep \
  'networking.SocketServerExample' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
java -cp . networking.IntgenServer &
echo "Sleeping for 5 seconds again after IntgenServer start..."
sleep 5
java -cp . networking.IntgenClient localhost > intgen.out &
echo "Running IntgenClient for 0.1 seconds only..."
sleep 0.1
ps -ef | grep \
  'networking.IntgenClient' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
echo "Killing IntgenServer..."
ps -ef | grep \
  'networking.IntgenServer' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
java -cp . networking.NonblockingSingleFileHttpServer build.xml 8084 &
echo "Sleeping for 5 seconds again after NonblockingSingleFileHttpServer start..."
sleep 5
curl -v http://localhost:8084/
ps -ef | grep \
  'networking.NonblockingSingleFileHttpServer' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
java -cp . networking.DaytimeUDPServer &
echo "Sleeping for 5 seconds again after DaytimeUDPServer start..."
sleep 5
java -cp . networking.DaytimeUDPClient localhost 1313
echo "Killing DaytimeUDPServer..."
ps -ef | grep \
  'networking.DaytimeUDPServer' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
java -cp . networking.UDPDiscardServer 9999 &
echo "Sleeping for 5 seconds again after UDPDiscardServer start..."
sleep 5
java -cp . networking.UDPDiscardClient localhost 9999 < UDPEcho.txt
echo "Killing UDPDiscardServer..."
ps -ef | grep \
  'networking.UDPDiscardServer' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
java -cp . networking.FastUDPDiscardServer 9999 &
echo "Sleeping for 5 seconds again after UDPFastDiscardServer start..."
sleep 5
java -cp . networking.UDPEchoClient localhost 9999 < UDPEcho.txt
echo "Killing FastUDPDiscardServer..."
ps -ef | grep \
  'networking.FastUDPDiscardServer' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
java -cp . networking.UDPEchoServer 7777 &
echo "Sleeping for 5 seconds again after UDPEchoServer start..."
sleep 5
java -cp . networking.UDPEchoClient localhost 7777 < UDPEcho.txt
echo "Killing UDPEchoServer..."
ps -ef | grep \
  'networking.UDPEchoServer' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
java -cp . networking.UDPDiscardServerWithChannels 9999 &
echo "Sleeping for 5 seconds again after UDPDiscardServerWithChannels start..."
sleep 5
java -cp . networking.UDPEchoClientWithChannels localhost 9999
echo "Killing UDPDiscardServerWithChannels..."
ps -ef | grep \
  'networking.UDPDiscardServerWithChannels' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
java -cp . networking.UDPEchoServerWithChannels 7777 &
echo "Sleeping for 5 seconds again after UDPEchoServerWithChannels start..."
sleep 5
java -cp . networking.UDPEchoClientWithChannels localhost 7777
echo "Killing UDPEchoServerWithChannels..."
ps -ef | grep \
  'networking.UDPEchoServerWithChannels' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
java -cp . networking.MulticastSniffer 239.255.255.250 1900 &
echo "Sleeping for 5 seconds again after MulticastSniffer start..."
sleep 5
java -cp . networking.MulticastSender all-systems.mcast.net 4000 
echo "Killing MulticastSniffer..."
ps -ef | grep \
  'networking.MulticastSniffer' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
java -cp . networking.TCPEchoServer &
echo "Sleeping for 5 seconds again after TCPEchoServer start..."
sleep 5
java -cp . networking.TCPEchoClient < TCPEcho.txt 
echo "Killing TCPEchoServer..."
ps -ef | grep \
  'networking.TCPEchoServer' | \
  grep -v grep | \
  awk '{print $2}' \
  | parallel -I% kill %
echo $?
