#!/usr/bin/env bash
require() {
  hash "$@" || exit 127
}
require java sleep
java --add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --module-path dist/NIOIntro*.jar --module niotutorial/com.javacodegeeks.niotutorial.server.Server &
echo "Sleeping for five seconds to let server be ready..."
sleep 5
