#!/usr/bin/env bash
require() {
hash "$@" || exit 127;
}
require java sleep 
java -cp . com.javacodegeeks.niotutorial.server.Server &
echo "Sleeping for five seconds to let server be ready..."
sleep 5
