#!/usr/bin/env bash
rmiregistry &
echo "Sleeping for 5 seconds after rmiregistry..."
sleep 5
java -cp . com.javacodegeeks.patterns.proxypattern.remoteproxy.ReportGeneratorImpl &
echo "Sleeping for 5 seconds again after server start..."
sleep 5
java -cp . stefano.lupo.Proxy &
echo "Sleeping for 5 seconds again after proxy start..."
sleep 5
java -Djava.rmi.server.codebase=http://java.shu.ac.uk/rmi -cp . remote.HelloServer &
echo "Sleeping for 5 seconds again after HelloServer start..."
sleep 5
java -cp . remote.Bank1Server &
echo "Sleeping for 5 seconds again after Bank1Server start..."
sleep 5
