#!/usr/bin/env bash
ps -ef | grep 'rmiregistry' | \
  awk '{print $2}' | head -1 \
  | parallel -I% kill %
echo $?
ps -ef | grep \
  'com.javacodegeeks.patterns.proxypattern.remoteproxy.ReportGeneratorImpl' | \
  awk '{print $2}' | head -1 \
  | parallel -I% kill %
echo $?
ps -ef | grep \
  'stefano.lupo.Proxy' | \
  awk '{print $2}' | head -1 \
  | parallel -I% kill %
echo $?
ps -ef | grep \
  'remote.HelloServer' | \
  awk '{print $2}' | head -1 \
  | parallel -I% kill %
echo $?
