#!/usr/bin/env bash
require() {
hash "$@" || exit 127;
}
require rmiregistry cp java sleep pgrep awk parallel 
rmiregistry &
echo "Sleeping for 5 seconds after rmiregistry..."
sleep 5
java -cp . com.javacodegeeks.patterns.proxypattern.remoteproxy.ReportGeneratorImpl &
echo "Sleeping for 5 seconds again after server start..."
sleep 5
java -cp . com.javacodegeeks.patterns.proxypattern.remoteproxy.ReportGeneratorClient
pgrep -an \
  'com.javacodegeeks.patterns.proxypattern.remoteproxy.ReportGeneratorImpl' | \
  awk '{print $1}' \
  | parallel -I% kill %
echo $?
java -cp . stefano.lupo.Proxy &
echo "Sleeping for 5 seconds again after proxy start..."
sleep 5
java -cp . stefano.lupo.TestProxy urls.txt
pgrep -an \
  'stefano.lupo.Proxy' | \
  awk '{print $1}' \
  | parallel -I% kill %
echo $?
java -Djava.security.policy=server.policy \
  -Djava.rmi.server.hostname=localhost \
  -Djava.rmi.server.codebase=file:///data/data/com.termux/files/home/LearnJava/Proxy/dist/helloserver-2.0.0.jar \
  -cp dist/helloserver-2.0.0.jar \
  remote.HelloServer &
echo "Sleeping for 5 seconds again after HelloServer start..."
sleep 5
java -Djava.security.policy=client.policy \
  -Djava.rmi.server.hostname=localhost \
  -Djava.rmi.server.codebase=file:///data/data/com.termux/files/home/LearnJava/Proxy/dist/helloserver-2.0.0.jar \
  -cp .:dist/helloclient-2.0.0.jar \
  remote.HelloClient
pgrep -an \
  'remote.HelloServer' | \
  awk '{print $1}' \
  | parallel -I% kill %
echo $?
java -cp . remote.Bank1Server &
echo "Sleeping for 5 seconds again after Bank1Server start..."
sleep 5
java -cp . remote.Bank1Client
pgrep -an \
  'remote.Bank1Server' | \
  awk '{print $1}' \
  | parallel -I% kill %
echo $?
