#!/usr/bin/env bash
(
  mod="lettuce.all"
  mkdir classes
  cp run.cp classes
  cd classes || exit 1
  JARS="$(cat run.cp)"
  IFS=':' read -ra jars <<<"$JARS"
  for i in "${jars[@]}"; do
    jar xvf "$i"
  done
  jarname="lettuce-all.jar"
  rm run.cp
  jar cf "$jarname" .
  jdeps --ignore-missing-deps --generate-module-info . "$jarname"
  jar xf "$jarname"
  mv "${mod}/module-info.java" .
  javac -p "$mod" -d . module-info.java
  #rm -rf module-info.java "$mod"
  jar uf "$jarname" -C . module-info.class
  cp "$jarname" ../dist
)
#rm -rf classes
exit 0
